### ISSUE TITLE
Cannot find module '@babel/plugin-transform-shorthand-properties'

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-gesture-handler#1765]
Library works fine in 1.10.3. Fails on 2.1.0.

```
  ● Test suite failed to run

  /node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector.js: Cannot find module '@babel/plugin-transform-shorthand-properties'
```

**Comment by UNIDY2002** [comment]
It turns out that I have to install both `@babel/preset-env` and `@babel/preset-typescript` as dependencies (or devDependencies) to make things work in my project.

**Comment by matasmaciulaitis** [comment]
I have exactly same issue, even though I am using `metro-react-native-babel-preset` and `@babel/plugin-transform-shorthand-properties` is included in it.

**Comment by SrBrahma** [comment]
Similar error here:

```
Android Bundling failed 20783ms
../node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /home/hb/Dev/Ahive/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: Cannot find module '@babel/preset-typescript'
Require stack:
- /home/hb/Dev/Ahive/node_modules/@babel/core/lib/config/files/plugins.js
- /home/hb/Dev/Ahive/node_modules/@babel/core/lib/config/files/index.js
- /home/hb/Dev/Ahive/node_modules/@babel/core/lib/index.js
- /home/hb/Dev/Ahive/node_modules/react-native-reanimated/plugin.js
- /home/hb/Dev/Ahive/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/module-types.js
- /home/hb/Dev/Ahive/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/configuration.js
- /home/hb/Dev/Ahive/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/index.js
- /home/hb/Dev/Ahive/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/index.js
- /home/hb/Dev/Ahive/node_modules/metro-react-native-babel-transformer/src/index.js
- /home/hb/Dev/Ahive/node_modules/metro-transform-worker/src/index.js
- /home/hb/Dev/Ahive/node_modules/metro/src/DeltaBundler/Worker.js
- /home/hb/Dev/Ahive/node_modules/jest-worker/build/workers/processChild.js
```

**Comment by UNIDY2002** [comment]
I think I've figured out the root cause of this issue (at least in my case).

The problem lies with **the inconsistency in the versions of `babel`-related packages in `yarn.lock`**.

To be specific, `metro-react-native-babel-transformer` requires `@babel/core@^7.14.0`, but my project `package.json` requires `@babel/core@7.16.5`. Just like the following require stack,

```
error node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /home/unidy/repos/THUInfoAdmin/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: Cannot find module '@babel/plugin-transform-shorthand-properties'
Require stack:
- /home/unidy/repos/THUInfoAdmin/node_modules/@babel/core/lib/config/files/plugins.js      <-- @babel/core@7.16.5
- /home/unidy/repos/THUInfoAdmin/node_modules/@babel/core/lib/config/files/index.js        <-- @babel/core@7.16.5
- /home/unidy/repos/THUInfoAdmin/node_modules/@babel/core/lib/index.js                     <-- @babel/core@7.16.5
- /home/unidy/repos/THUInfoAdmin/node_modules/react-native-reanimated/plugin.js
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/module-types.js         <-- @babel/core@^7.14.0
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/configuration.js        <-- @babel/core@^7.14.0
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/config/files/index.js                <-- @babel/core@^7.14.0
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/index.js                             <-- @babel/core@^7.14.0
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-react-native-babel-transformer/src/index.js
- /home/unidy/repos/THUInfoAdmin/node_modules/metro-transform-worker/src/index.js
- /home/unidy/repos/THUInfoAdmin/node_modules/metro/src/DeltaBundler/Worker.js
- /home/unidy/repos/THUInfoAdmin/node_modules/jest-worker/build/workers/processChild.js.
```
So it might bring confusion to babel, causing it to complain about being unable to find `@babel/plugin-transform-shorthand-properties`.

---

Simply downgrading `@babel/core` to `^7.14.0` might not solve the problem, as things get complicated due to the fact that **`react-native-codegen` indirectly requires `@babel/core@^7.1.6`**. Fortunately, there are some workarounds:
- add both `@babel/preset-env` and `@babel/preset-typescript` to the dependencies (or devDependencies) list of the project `package.json` file
- or simply delete `yarn.lock` and regenerate it

---

Finally, if there have to be someone responsible for the issue, at least the responsibility does not lies with `react-native-gesture-handler`. Perhaps `react-native` can do something to handle this issue.

**Comment by MonsterAnan** [comment]
@UNIDY2002 solved, you are right , thank you!

**Comment by Hanv2itedu** [comment]
Thanks, That work for me

**Comment by Gilmara-Git** [comment]
As I am not using typescript at the moment, installing only @babel/preset-env  as 'devDependencies' worked for me.
Solution is much appreciated!
Thanks

**Comment by LaVielle** [comment]
Deleting yarn.lock and reinstalling node_modules worked for me!
