### ISSUE TITLE
AppCenter build fails with RN 0.64.0 and gesture 10.3

### ISSUE THREAD

**Issue by vsheyanov** [software-mansion/react-native-gesture-handler#1425]
## Description

AppCenter build is failing with  RN 0.64.0 and react-native-gesture-handler 10.3 with an error:
```
/Users/runner/work/1/s/node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.h:9:52: error: expected a type
eventDispatcher:(nonnull RCTEventDispatcher *)eventDispatcher;
```

![image](https://user-images.githubusercontent.com/1764195/113681837-c356ce80-96c2-11eb-89eb-40988fb132fa.png)

I started digging and found this PR merged in August'20:
https://github.com/software-mansion/react-native-gesture-handler/pull/1160

Seems like imports were changed in iOS code. I reverted this change to check if it was causing for AppCenter to fail:
https://github.com/software-mansion/react-native-gesture-handler/compare/master...vsheyanov:master

Result - build is successful.

Important point - locally XCode build succeeds with gesture 10.3, only AppCenter fails.

AppCenter allows to configure XCode version and Node, I tried these:
Xcode: 11.7, 12.1, 12.4
Node: 10, 12

None of them worked with 10.3.

## Package versions

- React: 17.0.1
- React Native: 0.64.0
- React Native Gesture Handler: 10.3

@PeteTheHeat may be you have an idea why code added in your PR causes AppCenter to fail?

**Comment by vsheyanov** [comment]
Ok, after submitting the issue I want to check for X time if I missed something. I check what other dependencies are required for `react-navigation`
```
npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
```
After that I checked all required steps for each of those dependencies.
For `react-native-gesture-handle` we didn't have this line in `index.js`:
```
import 'react-native-gesture-handler';
```
Other dependencies also had problems with configuration.
After fixing all installation steps, build on AppCenter went back to successful.

**Comment by jakub-gonet** [comment]
I just wanted to mention I created a [repro repository](https://github.com/jakub-gonet/rngh_rn_64_issue_1425) & integrated AppCenter:
![image](https://user-images.githubusercontent.com/12465392/113728218-2f065f00-96f6-11eb-9ca4-527f056ace28.png)

so this is a config issue (as you wrote).

**Comment by acidSnkj** [comment]
I dont quite understand, what config issue real is? Because the import of react-native-gesture-handler I have it in the index.js but still failing the build in appcenter but show up this error:

> The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Aire-cjemmqrfssgzcvgircazzurqhyyy/Build/Intermediates.noindex/ArchiveIntermediates/Aire/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNGestureHandler.build/Objects-normal/armv7/RNGestureHandlerManager.o /Users/runner/work/1/s/node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by acidSnkj** [comment]
Ok I update this lib to 1.10.3 and it work. I dont know why with the 1.7.0 fail

**Comment by h0nor** [comment]
> Ok, after submitting the issue I want to check for X time if I missed something. I check what other dependencies are required for `react-navigation`
> 
> ```
> npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
> ```
> 
> After that I checked all required steps for each of those dependencies.
> For `react-native-gesture-handle` we didn't have this line in `index.js`:
> 
> ```
> import 'react-native-gesture-handler';
> ```
> 
> Other dependencies also had problems with configuration.
> After fixing all installation steps, build on AppCenter went back to successful.

Hi @vsheyanov ,

Could you please elaborate on how you were able to solve this problem? I am having the same problem with my iOS build.

`npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view` -> Did you re-install al these packages?

> After that, I checked all required steps for each of those dependencies.

 -> what does this mean exactly?

`import 'react-native-gesture-handler';` -> I already have this on my index.js

> Other dependencies also had problems with configuration.

 -> what does that mean?

I started having this problem after upgrading from RB 0.63.2 to 0.65.0-rc.3 (had to do it to support targetSDK 30 on android). My gesture-handler version is 1.4.1. Upgrading the gesture-handler alone to 1.10.3 just created more build problems.

Below is the description of my problem:

[https://github.com/software-mansion/react-native-gesture-handler/issues/1543](https://github.com/software-mansion/react-native-gesture-handler/issues/1543)
I would really appreciate any help. Thanks.
