### ISSUE TITLE
Cannot find module 'react-native/Libraries/Animated/src/NativeAnimatedHelper'

### ISSUE THREAD

**Issue by huyvohcmc** [software-mansion/react-native-gesture-handler#1412]
## Description

I got this error when upgrading React Native version to 0.64.0:
```js
Cannot find module 'react-native/Libraries/Animated/src/NativeAnimatedHelper' from 'jest/customScript.js'

      30 |
      31 | // Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
    > 32 | jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper').mock('react-native-gesture-handler', () => {
         |      ^
      33 |   const View = require('react-native/Libraries/Components/View/View');
      34 |   return {
      35 |     State: {},

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (jest/customScript.js:32:6)
```

## Steps To Reproduce
- Upgrade React Native to version 0.64.0
- Upgrade React Native Gesture Handler from 1.6.1 to 1.10.3 (I couldn't build app with 1.6.1)
- Run yarn test

### Expected behavior
Tests pass normally.

### Actual behavior
The error described above.

## package.json
```json
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "./app/testUtils/setUp.js",
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
}
```

## jest/customScript.js
```js
// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper').mock('react-native-gesture-handler', () => {
  const View = require('react-native/Libraries/Components/View/View');
  return {
    State: {},
    PanGestureHandler: View,
    BaseButton: View,
    Directions: {},
  };
});
```

## Package versions

- React: 17.0.1
- React Native: 0.64.0
- React Native Gesture Handler: 1.10.3 (or 1.7.0, 1.8.0, all got the error)

**Comment by jakub-gonet** [comment]
Is it a problem with RNGH though? It's crashing on `jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper')` and it's unrelated to RNGH. Maybe it stopped working after RN 64 upgrade?

**Comment by samcampisi** [comment]
This is indeed not related to the library. The location of `NativeAnimatedHelper` changed in RN0.64. You would need to change it from:
`jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper')`

to:
`jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper')`

Then it stops crashing.

**Comment by huyvohcmc** [comment]
Thanks @samcampisi
