### ISSUE TITLE
Typings are incorrect for children props on TouchableWithoutFeedback

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-gesture-handler#1350]
## Description

Typings are incorrect for children props on TouchableWithoutFeedback. Works in 1.9.0. Breaks in 1.10.0

### Screenshots

```
src/apps/Complete/components/ListItem.tsx:94:6 - error TS2322: Type '{ children: Element; key: string; onLongPress: () => undefined; onPress: () => void; style: { flex: number; borderRadius: number; margin: number; backgroundColor: string; flexDirection: "row"; }; }' is not assignable to type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.

94     <TouchableWithoutFeedback
        ~~~~~~~~~~~~~~~~~~~~~~~~

src/components/KeyboardHandler/index.tsx:18:6 - error TS2322: Type '{ children: Element; onLayout: (event: LayoutChangeEvent) => void; onPress: () => void; style: { height: string; }; }' is not assignable to type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.

18     <TouchableWithoutFeedback
        ~~~~~~~~~~~~~~~~~~~~~~~~

src/components/Modal/index.tsx:105:8 - error TS2322: Type '{ children: Element; onPress: () => Promise<void>; testID: string | undefined; }' is not assignable to type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.

105       <TouchableWithoutFeedback
           ~~~~~~~~~~~~~~~~~~~~~~~~

src/components/Modal/index.tsx:109:12 - error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & GenericTouchableProps & RefAttributes<GenericTouchable>'.

109           <TouchableWithoutFeedback>
               ~~~~~~~~~~~~~~~~~~~~~~~~

```

## Steps To Reproduce

```
          <TouchableWithoutFeedback>
            <Text>Hello</Text>
          </TouchableWithoutFeedback>
```

## Package versions

- React: 16.14.0
- React Native: 0.63.4
- React Native Gesture Handler: 1.10.0

**Comment by jakub-gonet** [comment]
Fixed in #1345.
