### ISSUE TITLE
Latest release (1.9.0) breaks build

### ISSUE THREAD

**Issue by alina-beck** [software-mansion/react-native-gesture-handler#1235]
## Description

When running `npx react-native run-ios` the build fails with the following errors:

```
/Users/xxx/MyApp/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m:212:18:
error: property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'
      recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
                 ^
/Users/xxx/MyApp/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m:212:43:
error: use of undeclared identifier 'UIScrollTypeMaskAll'
      recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
```

Downgrading to 1.8.0 solves the issue.

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Gesture Handler: 1.9.0

**Comment by jakub-gonet** [comment]
What's your Xcode version? This probably comes from the #1128 PR, which bumped the minimal iOS version to 13 (requiring Xcode 11 to build).

**Comment by GZLiew** [comment]
yes I can confirm this as well too Im running 

React: 16.13.1
React Native: 0.63.2
React Native Gesture Handler: 1.9.0
XCode: 11.3.1

Downgraded back to 1.8.0 immediately works again

**Comment by alina-beck** [comment]
Same here: Xcode 11.3.1, simulator iOS version 13.3.

**Comment by jakub-gonet** [comment]
Could you try updating Xcode to the 11.4? Looks like [`allowedScrollTypesMask`](https://developer.apple.com/documentation/uikit/uipangesturerecognizer/3538978-allowedscrolltypesmask?language=objc) attribute is supported since 13.4+ iOS SDK which is [included](https://en.wikipedia.org/wiki/Xcode#11.x_series) in the 11.4 Xcode release.

11.4 was released in March (8 months ago) so I'm closing this as a configuration issue.

**Comment by alina-beck** [comment]
Can confirm that this works in Xcode 12.2! :tada:

**Comment by hitrik** [comment]
i comment during development this part at RNPanHandler.m and build works:

```text
  if (@available(iOS 13.4, *)) {
    bool enableTrackpadTwoFingerGesture = [RCTConvert BOOL:config[@"enableTrackpadTwoFingerGesture"]];
    if(enableTrackpadTwoFingerGesture){
      recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
    }
}
```

**Comment by AIsokjonov** [comment]
react-native-gesture-handler@1.8.0 did NOT work for me. However,

react-native-gesture-handler@1.7.0 worked.
XCode:  10.1, Simulator: 12.1
React-native: 0.63.4
React: 16.13.1

**Comment by jakub-gonet** [comment]
@AIsokjonov could you please provide more information? What exactly doesn't work for you?

**Comment by Dror-Bar** [comment]
Using an older version of `Xcode - 11.3.1`, I can confirm I had to use version 1.8.0 (not 1.9.0) to avoid this error.

**Comment by Stas-Buzunko** [comment]
@jakub-gonet cannot update to 11.4 because latest is 11.3.1 on Mojave :D

**Comment by KenCorma** [comment]
I am locked to Mojave as well.  Just needs to be wrapped in a conditional compile statement. 

https://github.com/software-mansion/react-native-gesture-handler/pull/1301

**Comment by pxl-live** [comment]
> Using an older version of `Xcode - 11.3.1`, I can confirm I had to use version 1.8.0 (not 1.9.0) to avoid this error.

SPENT 5 hours pulling my hair out thinking it was a mistake on my end after updating from react navigation 4 to 5... Im using RN Gesture Handler 1.8.0 and its working. 1.9.0 does not build! using Xcode version 11.3

**Comment by jakub-gonet** [comment]
This should be fixed in #1301 (db78d3c), you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix it locally.

**Comment by sourav-navsoft** [comment]
![Screenshot 2020-11-19 at 8 04 21 PM](https://user-images.githubusercontent.com/10461787/106862542-496b8e80-66ed-11eb-8d19-515c116d8ea8.png)
Commentout the line.

**Comment by sourav-navsoft** [comment]
![Screenshot 2021-02-04 at 1 32 00 PM](https://user-images.githubusercontent.com/10461787/106862609-5ee0b880-66ed-11eb-8b02-fd00652296a4.png)
comment out the line.
