### ISSUE TITLE
@babel/preset-typescript can not be found after upgrading React Native from 0.67.4 to 0.68.0 on android emulator

### ISSUE THREAD

**Issue by emclab** [software-mansion/react-native-gesture-handler#1995]
## Description
After upgrading React Native from 0.67.4 to 0.68.0, run-android shows a red screen on android emulator after launch. And can not find @babel/preset-typescript.

```
error: node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /Users/macair/Documents/code/js/xyz_app6/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/config/files/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/metro-transform-worker/src/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/jest-worker/build/workers/processChild.js
 BUNDLE  ./index.js 
```

### Platforms

- [ ] iOS
- [ x] Android
- [ ] Web

### Screenshots
![Screen Shot 2022-04-08 at 10 10 04 PM](https://user-images.githubusercontent.com/946013/162557419-2c260cb8-5eb3-4547-a8b0-b97499d079d7.png)

## Steps To Reproduce

1.

### Expected behavior
Without the error
### Actual behavior
module @babel/preset-typescript can't be found
## Snack or minimal code example

```
import {
  GestureHandlerRootView,
  PanGestureHandler,
  PinchGestureHandler,
  State,
  TouchableOpacity,
} from "react-native-gesture-handler";
```
## Package versions

- React:17.0.2
- React Native:0.68.0
- React Native Gesture Handler:2.3.2
- React Native Reanimated:2.5.0

**Comment by j-piasecki** [comment]
Hi! It's possible that this error is caused by Reanimated - https://github.com/software-mansion/react-native-reanimated/issues/2746, as the worklet plugin is using `@babel/preset-typescript`.
You can try deleting `node_modules`, installing your dependencies again and clearing the metro cache (`yarn start --resetCache`) for good measure.
If that doesn't help, installing it using `yarn add -D @babel/preset-typescript` should solve the problem for now.
