### ISSUE TITLE
compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by cbjs** [software-mansion/react-native-gesture-handler#343]
after upgrading react-native from 0.57.1 to 0.57.5, complile failed.

here is the error log

> Task :react-native-gesture-handler:compileReleaseJavaWithJavac FAILED
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:16: error: package com.facebook.react.module.annotations does not exist
import com.facebook.react.module.annotations.ReactModule;
                                            ^
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:19: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;
                                   ^
  symbol:   class UIBlock
  location: package com.facebook.react.uimanager
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:40: error: cannot find symbol
@ReactModule(name=RNGestureHandlerModule.MODULE_NAME)
 ^
  symbol: class ReactModule
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.java:4: error: package com.facebook.react.module.annotations does not exist
import com.facebook.react.module.annotations.ReactModule;
                                            ^
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootViewManager.java:17: error: cannot find symbol
@ReactModule(name = RNGestureHandlerRootViewManager.REACT_CLASS)
 ^
  symbol: class ReactModule
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java:196: error: cannot find symbol
  @ReactProp(name = ViewProps.BORDER_RADIUS)
                             ^
  symbol:   variable BORDER_RADIUS
  location: class ViewProps
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:574: error: cannot find symbol
    final int rootViewTag = uiManager.resolveRootTagFromReactTag(ancestorViewTag);
                                     ^
  symbol:   method resolveRootTagFromReactTag(int)
  location: variable uiManager of type UIManagerModule
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:582: error: cannot find symbol
        if (root.getRootView().getRootViewTag() == rootViewTag) {
                              ^
  symbol:   method getRootViewTag()
  location: class ReactRootView
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:598: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock() {
                             ^
  symbol:   class UIBlock
  location: class RNGestureHandlerModule
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:634: error: cannot find symbol
    int rootViewTag = uiManager.resolveRootTagFromReactTag(viewTag);
                               ^
  symbol:   method resolveRootTagFromReactTag(int)
  location: variable uiManager of type UIManagerModule
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:641: error: cannot find symbol
        if (root.getRootView().getRootViewTag() == rootViewTag) {
                              ^
  symbol:   method getRootViewTag()
  location: class ReactRootView
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:41: error: method init in class Event<T> cannot be applied to given types;
    super.init(handler.getView().getId());
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:45: error: method init in class Event<T> cannot be applied to given types;
    super.init(handler.getView().getId());
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerPackage.java:18: error: RNGestureHandlerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNGestureHandlerPackage implements ReactPackage {
       ^
/Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNViewConfigurationHelper.java:44: error: cannot find symbol
      return parent.getChildAt(((ReactViewGroup) parent).getZIndexMappedChildIndex(index));
                                                        ^
  symbol:   method getZIndexMappedChildIndex(int)
  location: class ReactViewGroup
Note: /Users/cbjs/dev/novelsearcher/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
15 errors

FAILURE: Build failed with an exception.

**Comment by kenniga** [comment]
No one raise this issue? I've got same problem here.

**Comment by akkariyassine** [comment]
same problem here !

**Comment by osdnk** [comment]
Hi, @cbjs @akkariyassine 
Do you still face the issue? If yes, please provide more information about version or RN and RNGH. Please add Android version. It will be the best if you device to prepare some repo for reproducing the problem.

**Comment by kingbeful** [comment]
I've resolved this by change the build.gradle of react-native-gesture-handler

from:
`compileOnly 'com.facebook.react:react-native:+'`

to:
`compileOnly 'com.facebook.react:react-native:0.57.5'`

It's weird that seems without this change the run-android command does not read from 0.57.5.

If someone knows the reason, pls explain to me

**Comment by Ciberusps** [comment]
Lost 6h on fix. Locally build worked but in VS Appcenter cloud build was failed several times. I notices that v1.1.0 released recently(7h ago) and decided to check local version it was "^1.0.16", in cloud of course it transformed in 1.1.0 due to "^".

Fix downgrade from 1.1.0 -> 1.0.16 and use exact version(-E):
` npm i react-native-gesture-handler@1.0.16 -D -E`

**Comment by denissb** [comment]
@osdnk - the issue is `react-native-gesture-handler` > `1.0.16` uses `getOverflow` method from `ReactViewGroup.java` which was introduced since RN version `0.58.2`, so basically Android support for the latest version starts from `0.58.2`
See: [ReactViewGroup.java](https://github.com/facebook/react-native/blob/a289b7efb0d63881991d626da85df78cd2131c14/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java#L649)

**Comment by philjoseph** [comment]
So that means that this library will not work with RN versions < 0.58 ? I want to use it in my app that is still with 0.53.3, shall I give up ?

**Comment by osdnk** [comment]
Yes, well, it calls for being better documented. You may use older version of RNGH as well

**Comment by philjoseph** [comment]
Thanks @osdnk - which one shall work for my RN version. I am actually not using RNGH directly but through https://github.com/react-navigation/react-navigation? Shall I use 1.0.15 and expect to get it work with react-navigation ?

**Comment by osdnk** [comment]
Everything below 1.1.0

**Comment by kunal886496** [comment]
error: package com.facebook.react.module.annotations does not exist
import com.facebook.react.module.annotations.ReactModule;
                                            ^
/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:19: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;



I am tired of facing this again and again

**Comment by DmitriyNikolenko** [comment]
I deleted yarn.lock and node_modules, run yarn install and problem disappeared. Magic!

**Comment by kunal886496** [comment]
I am using npm and i have tried everything like this. But its still not working.

**Comment by SevdaCimen** [comment]
> Lost 6h on fix. Locally build worked but in VS Appcenter cloud build was failed several times. Accidentally I noticed that v1.1.0 released recently(7h ago) and decided to check local version it was "^1.0.16", and in cloud of course it transformed in 1.1.0 due to "^".
> 
> Fix - downgrade from 1.1.0 -> 1.0.16 and use exact version(-E):
> ` npm i react-native-gesture-handler@1.0.16 -D -E`

Great Thank you its work!

**Comment by dhee9000** [comment]
I'm facing this issue now after installing expo's unimodules and the camera module on top of my existing RN project which previously had this package already installed. None of the listed fixes work, I tried deleting node_modules and yarn.lock and re-installing all the packages again, I tried forcing version 1.0.16 (but I am using RN ver 0.58.5 so this shouldn't be an issue according to the comments). I still get the same error. My output log is as follows
``` 
> Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:16: error: package com.facebook.react.module.annotations does not exist
import com.facebook.react.module.annotations.ReactModule;
                                            ^
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:19: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;
                                   ^
  symbol:   class UIBlock
  location: package com.facebook.react.uimanager
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:40: error: cannot find symbol
@ReactModule(name=RNGestureHandlerModule.MODULE_NAME)
 ^
  symbol: class ReactModule
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootViewManager.java:4: error: package com.facebook.react.module.annotations does not exist
import com.facebook.react.module.annotations.ReactModule;
                                            ^
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootViewManager.java:17: error: cannot find symbol
@ReactModule(name = RNGestureHandlerRootViewManager.REACT_CLASS)
 ^
  symbol: class ReactModule
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java:218: error: cannot find symbol
  @ReactProp(name = ViewProps.BORDER_RADIUS)
                             ^
  symbol:   variable BORDER_RADIUS
  location: class ViewProps
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:41: error: method init in class Event<T> cannot be applied to given types;
    super.init(handler.getView().getId());
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:574: error: cannot find symbol
    final int rootViewTag = uiManager.resolveRootTagFromReactTag(ancestorViewTag);
                                     ^
  symbol:   method resolveRootTagFromReactTag(int)
  location: variable uiManager of type UIManagerModule
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:582: error: cannot find symbol
        if (root.getRootView().getRootViewTag() == rootViewTag) {
                              ^
  symbol:   method getRootViewTag()
  location: class ReactRootView
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:598: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock() {
                             ^
  symbol:   class UIBlock
  location: class RNGestureHandlerModule
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:634: error: cannot find symbol
    int rootViewTag = uiManager.resolveRootTagFromReactTag(viewTag);
                               ^
  symbol:   method resolveRootTagFromReactTag(int)
  location: variable uiManager of type UIManagerModule
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:641: error: cannot find symbol
        if (root.getRootView().getRootViewTag() == rootViewTag) {
                              ^
  symbol:   method getRootViewTag()
  location: class ReactRootView
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerPackage.java:18: error: RNGestureHandlerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNGestureHandlerPackage implements ReactPackage {
       ^
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:45: error: method init in class Event<T> cannot be applied to given types;
    super.init(handler.getView().getId());
         ^
  required: int,long
  found: int
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Event declared in class Event
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNViewConfigurationHelper.java:45: error: cannot find symbol
      return parent.getChildAt(((ReactViewGroup) parent).getZIndexMappedChildIndex(index));
                                                        ^
  symbol:   method getZIndexMappedChildIndex(int)
  location: class ReactViewGroup
C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNViewConfigurationHelper.java:54: error: cannot find symbol
            String overflow = ((ReactViewGroup) view).getOverflow();
                                                     ^
  symbol:   method getOverflow()
  location: class ReactViewGroup
Note: C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
16 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
197 actionable tasks: 144 executed, 53 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (C:\Users\dheeraj\Documents\Ripplify\repos\ripplify-app\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by shubham-2710** [comment]
> Lost 6h on fix. Locally build worked but in VS Appcenter cloud build was failed several times. Accidentally I noticed that v1.1.0 released recently(7h ago) and decided to check local version it was "^1.0.16", and in cloud of course it transformed in 1.1.0 due to "^".
> 
> Fix - downgrade from 1.1.0 -> 1.0.16 and use exact version(-E):
> ` npm i react-native-gesture-handler@1.0.16 -D -E`

Great, Thanks it works.

**Comment by LiuC520** [comment]
same problem here !

**Comment by youngjuning** [comment]
same problem here !

**Comment by wuwenyuan111** [comment]
https://github.com/facebook/react-native/issues/25292#issuecomment-503070043
It works.

**Comment by Joltik** [comment]
react-native 0.60.4

**Comment by Joltik** [comment]
react-native  v0.60.4
android->app->build.gradle

**Comment by jakub-gonet** [comment]
This should be resolved on newer versions of RN, so I'm closing it.
