### PR TITLE
Cocoapods: Fix deprecated/removed File.exists method 

### PR DESCRIPTION
**Pull request by NoumanSakhawat**
## Description
When I upgraded Ruby on accident to 3 - that my pod install failed with:
```
[!] Invalid 'Podfile' file: 
[!] Invalid 'RNGestureHandler.podspec' file: undefined method 'exists?' for File:Class.

 # from /Users/xx/iOSProjects/xx-app/node_modules/react-native-gesture-handler/RNGestureHandler.podspec:5
 # -------------------------------------------
 # reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >  config = find_config()
 ```
 
 Resolves the removed method of File.exists in Ruby3. The alternative method of File.exist is recommended and already exists on 2.5 for no breaking changes.

https://rubyapi.org/2.5/o/file#method-c-exist-3F

## Test plan
A local working `pod install`

### CODE REVIEW

**Comment by tomekzaw** [comment]
Duplicate of #2368

**Comment by j-piasecki** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/2368 has been merged, so I'll close this one.

**Comment by j-piasecki** [comment]
@Miigaarino It's included in 2.9.0!
