### ISSUE TITLE
RNGestureHandlerManager.h:9:52: error: expected a type - eventDispatcher:(nonnull RCTEventDispatcher *)eventDispatcher;

### ISSUE THREAD

**Issue by h0nor** [software-mansion/react-native-gesture-handler#1543]
## Description

Cannot build iOS app after upgrading from RN version 0.63.2 to 0.65.0-rc.3. I am getting this error:

> In file included from /Users/.../ReactNativeProjects/.../node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.m:1:
> /Users/.../ReactNativeProjects/.../node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.h:9:52: error: expected a type
>                           eventDispatcher:(nonnull RCTEventDispatcher *)eventDispatcher;

Problem is in RNGestureHandlerManager.h, on the line below:

```
- (nonnull instancetype)initWithUIManager:(nonnull RCTUIManager *)uiManager
                          eventDispatcher:(nonnull RCTEventDispatcher *)eventDispatcher;
```

<img width="804" alt="gh1" src="https://user-images.githubusercontent.com/30260964/128780850-8b419261-aad3-4bf1-8baf-14915759dcfc.png">

Edit: When I upgrade to RNGestureHandler version 1.10.3 I get the errors below:
<img width="438" alt="Screen Shot 2021-08-11 at 22 00 54" src="https://user-images.githubusercontent.com/30260964/129087822-c662cc7e-5665-48b4-8896-68acaae9a723.png">

## Steps To Reproduce

1. Upgrade to the latest version of RN and try to build the app.

### Expected behavior

The app should build successfully. 

### Actual behavior

Build fails.

## Package versions

react-native-gesture-handler@1.4.1
react-native@0.65.0-rc.3
XCode: 12.2

**Comment by roskyba** [comment]
I am experiencing the same issue. Tried to remove pods and cleaning the build folder - didn't help. Also tried upgrading package with no succes

**Comment by LBojanic** [comment]
`#import <React/RCTEventDispatcher.h>` solved for me

**Comment by becky-intelletive** [comment]
@LBojanic - where did you add that import?

**Comment by qasimmehdi** [comment]
> @LBojanic - where did you make that change?

At the top of the same file. in RNGestureHandlerManager.h

**Comment by aditya-keri-betterhalf** [comment]
> > @LBojanic - where did you make that change?
> 
> At the top of the same file. in RNGestureHandlerManager.h

If I'm not wrong, I'll have to do this every time I have a clean build right ?
Could you please tell me what the permanent solution to this issue is ? I'm facing this after upgrading from 0.63.3 to 0.64.2.
My gesture handler version is `1.6.0`

**Comment by qasim-appiskey** [comment]
No once you add that line it should stay there until you clone the project somewhere else and run npm install.

**Comment by aditya-keri-betterhalf** [comment]
> @aditya-keri-betterhalf No once you add that line it should stay there until you clone the project somewhere else and run npm install.

Any idea what's the right way to fix this then ?
Will upgrading the gesture handler version to latest help ?

**Comment by qasim-appiskey** [comment]
@aditya-keri-betterhalf look at this file https://github.com/software-mansion/react-native-gesture-handler/blob/master/ios/RNGestureHandlerManager.h it has `@class RCTEventDispatcher;` so you upgrading should fix it but if you are using any other libraries that requires a specific version of gesture handler that upgrading will not work.

**Comment by UberMC** [comment]
To Solve:
```
yarn upgrade react-native-gesture-handler
cd ios
pod install
```

Most likely you installed react-native-gesture-handler with react-navigation so it's using an older version unsupported by RN update.

**Comment by piaskowyk** [comment]
It looks like a cache issue. I recommend to run: `rm -rf ./node_modules && yarn && cd ios & pod deintegrate && pod install`

**Comment by hokimtam** [comment]
> `#import <React/RCTEventDispatcher.h>` solved for me

Saved my life. Thanks.

**Comment by Simon-44** [comment]
Adding the line works, but cleaning the project removes it.
I added the react-native-gesture-handler library, but it doesn't solve this.
Is it possible that another library uses the same lib in a previous version and then erase the version I added?

**Comment by hokimtam** [comment]
> Adding the line works, but cleaning the project removes it. I added the react-native-gesture-handler library, but it doesn't solve this. Is it possible that another library uses the same lib in a previous version and then erase the version I added?

You should use patch-package to save node_modules changes and apply it after cleaning.
