### ISSUE TITLE
App crashes on tap on text-input from gesture handler

### ISSUE THREAD

**Issue by nirajsinghapr9** [software-mansion/react-native-gesture-handler#3621]
### Description

 java.lang.NoSuchMethodError: No virtual method reversed()Ljava/util/List; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.makeActive(GestureHandlerOrchestrator.kt:193)
	at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.tryActivate(GestureHandlerOrchestrator.kt:102)
	at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.kt:154)
	at com.swmansion.gesturehandler.core.GestureHandler.moveToState(GestureHandler.kt:568)
	at com.swmansion.gesturehandler.core.GestureHandler.activate(GestureHandler.kt:671)
	at com.swmansion.gesturehandler.core.GestureHandler.activate(GestureHandler.kt:667)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.tryCancelAllHandlers(RNGestureHandlerRootHelper.kt:112)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.requestDisallowInterceptTouchEvent(RNGestureHandlerRootHelper.kt:93)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.requestDisallowInterceptTouchEvent(RNGestureHandlerRootView.kt:47)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.requestDisallowInterceptTouchEvent(CoordinatorLayout.java:622)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.widget.ScrollView.requestDisallowInterceptTouchEvent(ScrollView.java:1087)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:4043)
	at com.facebook.react.views.textinput.ReactEditText.onTouchEvent(ReactEditText.java:250)
	at android.view.View.dispatchTouchEvent(View.java:15199)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:868)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:38)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### Steps to reproduce

Just use textinput and click on it
Android target SDK is 35

### A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.

https://github.com/software-mansion/react-native-gesture-handler/issues

### Gesture Handler version

2.17.1

### React Native version

0.72.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

Galaxy a50 (13)

### Acknowledgements

Yes

**Comment by m-bert** [comment]
HI @nirajsinghapr9! Does this happen on newer versions? `2.17.1` and `0.72.5` are far behind current ones.

**Comment by m-bert** [comment]
Also, please provide a reproduction code.

**Comment by brandonrichards-promaxdev** [comment]
I'm running into this issue as well. This is after upgrading Android compileSdk from 34 to 35 and running my app on an SDK <35. I believe this is related to these behavior changes in SDK 35: https://developer.android.com/about/versions/15/behavior-changes-15#openjdk-api-changes.
> If an app is re-compiled with compileSdk set to 35 and minSdk set to 34 or lower, and then the app is run on Android 14 and lower, a runtime error is thrown: `java.lang.NoSuchMethodError: No virtual method
removeFirst()Ljava/lang/Object; in class Ljava/util/ArrayList;`

**Comment by mukesh2309** [comment]
any solution on this i'm also facing same issue ? on 34 it works perfectly but 35 it's giving exact above error

**Comment by nirajsinghapr9** [comment]
@mukesh2309  i have created a patch as a temporary solution.

Go to node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt

at line 193 change `awaitingHandlers.reversed()` to `awaitingHandlers.asReversed()`

**Comment by mukesh2309** [comment]
@nirajsinghapr9 bro !!! you saved my time !!!!

**Comment by m-bert** [comment]
Oh my bad, I didn't look carefully at the exact stack trace when I saw outdated versions. This was fixed in https://github.com/software-mansion/react-native-gesture-handler/pull/3598. Let me know if this issue persists after this PR. If so, I'll reopen it.

**Comment by Smit-Kadawala** [comment]
> [@mukesh2309](https://github.com/mukesh2309) i have created a patch as a temporary solution.
> 
> Go to node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt
> 
> at line 193 change `awaitingHandlers.reversed()` to `awaitingHandlers.asReversed()`

Working, Thank You
