### ISSUE TITLE
global.__reanimatedWorkletInit is not a function

### ISSUE THREAD

**Issue by ethanneff** [software-mansion/react-native-gesture-handler#1778]
Breaks on 2.1.0. Works on 1.10.3.

```sh
  ● Test suite failed to run

    TypeError: global.__reanimatedWorkletInit is not a function

      at node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager.ts:11:36
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager.ts:11:36)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector.tsx:20:1)

```

**Comment by j-piasecki** [comment]
Hi! It seems to be the same problem as https://github.com/software-mansion/react-native-reanimated/issues/1380. Would you mind trying out the answers posted there to see if they work for you?

**Comment by maximilize** [comment]
> Hi! It seems to be the same problem as [software-mansion/react-native-reanimated#1380](https://github.com/software-mansion/react-native-reanimated/issues/1380). Would you mind trying out the answers posted there to see if they work for you?

For me this worked.
