### ISSUE TITLE
FlatList `measureLayoutRelativeToContainingList` error

### ISSUE THREAD

**Issue by ShaMan123** [software-mansion/react-native-gesture-handler#707]
I'm working on RN0.60+.
Seems that something changed in [react-native/Libraries/Lists/VirtualizedList.js](https://github.com/facebook/react-native/blob/84f5ebe4f941e752ba96b4d4a75dc6c6f5faa665/Libraries/Lists/VirtualizedList.js#L1185) and therefore this error shows up.
This happens when:
```js
import { FlatList as RNFlatList } from 'react-native';
import { FlatList } from 'react-native-gesture-handler';


<RNFlatList 
   renderScrollComponent={(props) => <ScrollView {...props} />} 
/>

//  OR

<FlatList />
```

I'm getting 
```js
undefined is not a function (near '...this._scrollRef.measureLayout...')
```

RNGH version: 1.3.0, I'm using a clone even with this repo.

**Comment by ShaMan123** [comment]
Is this related to passing `ref={React.createRef()}`?

**Comment by kesha-antonov** [comment]
Same here after using `FlatList` from this lib
Any fix?

**Comment by sivakumar-cf** [comment]
Any update on this? happening after RN0.60+ update.

**Comment by StefanWegener** [comment]
Same issue after RN0.61.5 using react-native and react-native-gesture-handler

**Comment by fozzarelo** [comment]
Seeing this too under the same conditions. I'm getting a warning only, and the functionality is still there. Are you guys getting crashing errors?

**Comment by james1888** [comment]
I got the same error as well.

**Comment by oguzhanun** [comment]
When using two nested FlatLists (imported from 'react-native-gesture-handler'), I got the same error. But after changing the inner FlatList to ScrollView, the error disappeared.

**Comment by Babar-Memon** [comment]
import FlatList from 'react-native'

**Comment by namphd00769** [comment]
> When using two nested FlatLists (imported from 'react-native-gesture-handler'), I got the same error. But after changing the inner FlatList to ScrollView, the error disappeared.

Yes, I have same issues when using two nested FlatList

**Comment by cklinx** [comment]
Same Here

**Comment by matapo** [comment]
Same error using two nested horizontal FlatLists (from 'react-native-gesture-handler').

**Comment by nnabinh** [comment]
Any progress on this?

**Comment by bwoodlt** [comment]
Any updates on this issue?

**Comment by wzahedi** [comment]
Using the regular FlatList from react native makes this error go away, however I need the FlatList to respond to nested gestures from a larger list, so this won't work for my use. Any updates on this would be appreciated.

**Comment by fabianlee1211** [comment]
I have this issue as well for a FlatList with filters. If I spam the filters rapidly so it's constantly changing the list content, I suppose somehow it cannot respond quickly with the layout measurement? 
Setting the `getItemLayout` prop does help though. Just curious if there's another way.

**Comment by pedrocunha** [comment]
Hi folks - any news updates on this?

**Comment by piaskowyk** [comment]
I tested it on `1.10.2` and everything seems to work, so I recommend updating the gesture-handler version in your project.
let me know if something is still broken.
